-- 3th party dependencies
add_requires("libcurl", {system = false, configs = {shared = false}})
add_requires("openssl", {system = false, configs = {shared = false}})
add_requires("gtest", {system = false, configs = {shared = false}})

-- common rules
add_rules("mode.release", "mode.debug")
set_languages("c++20")
add_includedirs("./")

target("common")
    set_kind("static")
    add_files("common/src/*.cpp")
    add_headerfiles("common/unit-tests/*.cpp")
    add_headerfiles("common/*.hpp", "common/*.md")
target_end()

target("exmo_api")
    set_kind("static")
    add_files("exmo_api/src/*.cpp")
    add_headerfiles("exmo_api/unit-tests/*.cpp")
    add_headerfiles("exmo_api/*.hpp", "exmo_api/*.md")
    add_packages("libcurl", "openssl")
target_end()

target("TB")
    set_kind("binary")
    add_files("src/TB.cpp")
    add_headerfiles("*.md")
    add_packages("libcurl", "openssl")
    add_deps("exmo_api")
target_end()

target("UnitTests")
    set_kind("binary")
    add_files("src/UnitTests.cpp")
    add_files("**/unit-tests/*.cpp")
    add_packages("libcurl", "openssl", "gtest")
    add_deps("exmo_api")
target_end()
